DATASET_ROOT: "../bdataset_stereo"
JSON_PATH: "train1.json"
BATCH_SIZE: 2
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.01
MOMENTUM: 0.8
WEIGHT_DECAY: 0.0001
DAMPENING: 0.2

MILESTONES: [150]
GAMMA: .1

NUM_EPOCHS: 150
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"