DATASET_ROOT: "../bdataset_stereo"
JSON_PATH: "train1.json"
BATCH_SIZE: 2
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.001
BETAS: [0.9, 0.999]
EPS: 0.00001
WEIGHT_DECAY: 0.00001

MILESTONES: [150]
GAMMA: 0.1

NUM_EPOCHS: 200
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"