DATASET_ROOT: "../bdataset_stereo"
JSON_PATH: "train.json"
BATCH_SIZE: 2
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.1
MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001
DAMPENING: 0.1

MILESTONES: [150]
GAMMA: .1

NUM_EPOCHS: 300
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"